name: Tests
on:
  pull_request:
  push:
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-requests python3-stevedore python3-prettytable python3-serial python3-flask python3-pytest
          pytest-3 tests
          
